export const QUICK_CATALOG = [
{ id:'mercearia',label:'Mercearia',emoji:'🥫',subtypes:[
{id:'cafe-padaria',label:'Café da manhã / Padaria',items:[['Achocolatado','mercearia'],['Adoçante','mercearia'],['Açúcar','mercearia'],['Biscoito','mercearia'],['Bolo','mercearia'],['Café','mercearia'],['Cereais','mercearia'],['Chá','mercearia'],['Geleia','mercearia'],['Iogurte','frios'],['Manteiga','frios'],['Pão','frios'],['Requeijão','frios'],['Torrada','mercearia']]},
{id:'mercearia-geral',label:'Mercearia em geral e enlatados',items:[['Amido de milho','mercearia'],['Arroz','mercearia'],['Atum','mercearia'],['Aveia em flocos','mercearia'],['Azeite','mercearia'],['Azeitona','mercearia'],['Barra de cereal','mercearia'],['Caldo de carne','mercearia'],['Catchup e mostarda','mercearia'],['Ervilha','mercearia'],['Farinha de milho','mercearia'],['Farinha de rosca','mercearia'],['Farinha de trigo','mercearia'],['Feijão','mercearia'],['Fermento','mercearia'],['Fubá','mercearia'],['Gelatina','mercearia'],['Grão de bico','mercearia'],['Leite condensado','mercearia'],['Macarrão','mercearia'],['Macarrão instantâneo','mercearia'],['Maionese','mercearia'],['Milho','mercearia'],['Molho de tomate','mercearia'],['Ovos','frios'],['Óleo','mercearia'],['Palmito','mercearia'],['Queijo ralado','frios'],['Sal','mercearia'],['Tempero pronto','mercearia'],['Vinagre','mercearia']]},
{id:'bebidas',label:'Bebidas',items:[['Água','bebidas'],['Cerveja','bebidas'],['Coca cola','bebidas'],['Energético','bebidas'],['Leite','frios'],['Refrigerante','bebidas'],['Suco','bebidas'],['Suco de uva','bebidas']]}]},
{ id:'geladeira',label:'Geladeira',emoji:'🥩',subtypes:[{id:'carnes-frios',label:'Carnes e frios',items:[['Bife bovino','carnes'],['Bife de fígado','carnes'],['Bisteca suína','carnes'],['Carne moída','carnes'],['Coxa e sobrecoxa de frango','carnes'],['Filé de frango','carnes'],['Hambúrguer','carnes'],['Linguiça','carnes'],['Mussarela','frios'],['Nuggets','carnes'],['Peixe','carnes'],['Presunto','frios'],['Queijo branco','frios'],['Salsicha','carnes']]}]},
{ id:'casa',label:'Casa e cuidados',emoji:'🧼',subtypes:[
{id:'limpeza-utilidades',label:'Produtos de limpeza / Utilidades',items:[['Água sanitária','limpeza'],['Água sanitária QBOA','limpeza'],['Álcool','limpeza'],['Amaciante','limpeza'],['Desinfetante','limpeza'],['Detergente','limpeza'],['Esponja','limpeza'],['Filtros de papel','limpeza'],['Filme plástico','limpeza'],['Fósforo','limpeza'],['Lustra-móveis','limpeza'],['Multiuso','limpeza'],['Palha de aço','limpeza'],['Palitos de dente','limpeza'],['Papel Alumínio','limpeza'],['Papel higiênico','limpeza'],['Papel toalha','limpeza'],['Pano de chão','limpeza'],['Rodo/vassoura','limpeza'],['Sabão em barra','limpeza'],['Sabão em pó','limpeza'],['Saco de lixo','limpeza'],['Velas','limpeza']]},
{id:'higiene-pessoal',label:'Higiene pessoal',items:[['Absorvente','limpeza'],['Acetona','limpeza'],['Algodão','limpeza'],['Condicionador','limpeza'],['Creme dental','limpeza'],['Desodorante','limpeza'],['Escova de dente','limpeza'],['Fio dental','limpeza'],['Hastes flexíveis','limpeza'],['Lâmina de barbear','limpeza'],['Papel higiênico','limpeza'],['Sabonete','limpeza'],['Shampoo','limpeza']]}]},
{ id:'feira',label:'Feira',emoji:'🍎',subtypes:[{id:'frutas-legumes',label:'Frutas e legumes',items:[['Abacaxi','hortifruti'],['Abobrinha','hortifruti'],['Abóbora','hortifruti'],['Alface','hortifruti'],['Alho','hortifruti'],['Banana','hortifruti'],['Batata','hortifruti'],['Batata doce','hortifruti'],['Berinjela','hortifruti'],['Beterraba','hortifruti'],['Brócolis','hortifruti'],['Cebola','hortifruti'],['Cenoura','hortifruti'],['Cheiro-verde','hortifruti'],['Chuchu','hortifruti'],['Couve-flor','hortifruti'],['Hortelã','hortifruti'],['Laranja','hortifruti'],['Limão','hortifruti'],['Maçã','hortifruti'],['Mamão','hortifruti'],['Mandioca','hortifruti'],['Maracujá','hortifruti'],['Melancia','hortifruti'],['Melão','hortifruti'],['Morango','hortifruti'],['Pepino','hortifruti'],['Pepinos','hortifruti'],['Quiabo','hortifruti'],['Repolho','hortifruti'],['Rúcula','hortifruti'],['Tomate','hortifruti'],['Uvas','hortifruti'],['Vagem','hortifruti']]}]},
{ id:'pet',label:'Pet',emoji:'🐾',subtypes:[{id:'pet-itens',label:'Pet',items:[['Petiscos','outros'],['Ração','outros']]}]}
];
