export const QUICK_CATALOG = [
{ id:'mercearia',label:'Mercearia',emoji:'🥫',subtypes:[
{id:'cafe-padaria',label:'Café da manhã / Padaria',items:[['Café','mercearia'],['Biscoito','mercearia'],['Cereais','mercearia'],['Achocolatado','mercearia'],['Chá','mercearia'],['Adoçante','mercearia'],['Açúcar','mercearia'],['Geleia','mercearia'],['Torrada','mercearia'],['Pão','frios'],['Requeijão','frios'],['Manteiga','frios'],['Iogurte','frios'],['Bolo','mercearia']]},
{id:'mercearia-geral',label:'Mercearia em geral e enlatados',items:[['Arroz','mercearia'],['Feijão','mercearia'],['Aveia em flocos','mercearia'],['Caldo de carne','mercearia'],['Gelatina','mercearia'],['Macarrão instantâneo','mercearia'],['Farinha de trigo','mercearia'],['Barra de cereal','mercearia'],['Fubá','mercearia'],['Grão de bico','mercearia'],['Palmito','mercearia'],['Ervilha','mercearia'],['Milho','mercearia'],['Farinha de milho','mercearia'],['Farinha de rosca','mercearia'],['Fermento','mercearia'],['Óleo','mercearia'],['Azeite','mercearia'],['Amido de milho','mercearia'],['Macarrão','mercearia'],['Azeitona','mercearia'],['Leite condensado','mercearia'],['Maionese','mercearia'],['Catchup e mostarda','mercearia'],['Tempero pronto','mercearia'],['Sal','mercearia'],['Ovos','frios'],['Queijo ralado','frios'],['Vinagre','mercearia'],['Molho de tomate','mercearia'],['Atum','mercearia']]},
{id:'bebidas',label:'Bebidas',items:[['Água','bebidas'],['Leite','frios'],['Refrigerante','bebidas'],['Cerveja','bebidas'],['Suco','bebidas'],['Energético','bebidas']]}]},
{ id:'geladeira',label:'Geladeira',emoji:'🥩',subtypes:[{id:'carnes-frios',label:'Carnes e frios',items:[['Bife bovino','carnes'],['Bisteca suína','carnes'],['Carne moída','carnes'],['Coxa e sobrecoxa de frango','carnes'],['Filé de frango','carnes'],['Linguiça','carnes'],['Salsicha','carnes'],['Nuggets','carnes'],['Queijo branco','frios'],['Presunto','frios'],['Mussarela','frios'],['Peixe','carnes'],['Hambúrguer','carnes']]}]},
{ id:'casa',label:'Casa e cuidados',emoji:'🧼',subtypes:[
{id:'limpeza-utilidades',label:'Produtos de limpeza / Utilidades',items:[['Papel higiênico','limpeza'],['Detergente','limpeza'],['Sabão em pó','limpeza'],['Sabão em barra','limpeza'],['Água sanitária','limpeza'],['Desinfetante','limpeza'],['Lustra-móveis','limpeza'],['Saco de lixo','limpeza'],['Papel toalha','limpeza'],['Álcool','limpeza'],['Amaciante','limpeza'],['Pano de chão','limpeza'],['Esponja','limpeza'],['Palha de aço','limpeza'],['Multiuso','limpeza'],['Filme plástico','limpeza'],['Papel Alumínio','limpeza'],['Fósforo','limpeza'],['Filtros de papel','limpeza'],['Palitos de dente','limpeza'],['Velas','limpeza'],['Rodo/vassoura','limpeza']]},
{id:'higiene-pessoal',label:'Higiene pessoal',items:[['Papel higiênico','limpeza'],['Sabonete','limpeza'],['Creme dental','limpeza'],['Escova de dente','limpeza'],['Hastes flexíveis','limpeza'],['Fio dental','limpeza'],['Absorvente','limpeza'],['Shampoo','limpeza'],['Condicionador','limpeza'],['Acetona','limpeza'],['Algodão','limpeza'],['Lâmina de barbear','limpeza'],['Desodorante','limpeza']]}]},
{ id:'feira',label:'Feira',emoji:'🍎',subtypes:[{id:'frutas-legumes',label:'Frutas e legumes',items:[['Abacaxi','hortifruti'],['Laranja','hortifruti'],['Banana','hortifruti'],['Limão','hortifruti'],['Mamão','hortifruti'],['Maçã','hortifruti'],['Melão','hortifruti'],['Melancia','hortifruti'],['Abóbora','hortifruti'],['Abobrinha','hortifruti'],['Batata','hortifruti'],['Tomate','hortifruti'],['Cebola','hortifruti'],['Alho','hortifruti'],['Cenoura','hortifruti'],['Pepino','hortifruti'],['Beterraba','hortifruti'],['Vagem','hortifruti'],['Berinjela','hortifruti'],['Chuchu','hortifruti'],['Alface','hortifruti'],['Brócolis','hortifruti'],['Rúcula','hortifruti'],['Cheiro-verde','hortifruti'],['Couve-flor','hortifruti'],['Mandioca','hortifruti'],['Batata doce','hortifruti'],['Hortelã','hortifruti'],['Maracujá','hortifruti'],['Quiabo','hortifruti'],['Repolho','hortifruti'],['Pepinos','hortifruti'],['Uvas','hortifruti'],['Morango','hortifruti']]}]},
{ id:'pet',label:'Pet',emoji:'🐾',subtypes:[{id:'pet-itens',label:'Pet',items:[['Ração','outros'],['Petiscos','outros']]}]}
];